import { AnalysisResponse } from "../types/insight.ts";
import { calculateReportingPeriod } from "./periodUtils.ts";

/**
 * Utility for exporting evidence-grounded client intelligence reports as
 * Markdown (.md), JSON (.json), or PDF Print.
 */
export function exportReportAsMarkdown(analysis: AnalysisResponse): void {
  const insight = analysis.insight;
  const daysCount = analysis.daysCovered.length || 1;
  const periodInfo = calculateReportingPeriod(daysCount);
  const clientName = insight.meta?.sourceLabel || "Client Consultation";
  const dateStr = new Date().toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const mdContent = `# ${periodInfo.title}
**Client / Session:** ${clientName}  
**Report Date:** ${dateStr}  
**Duration Analyzed:** ${periodInfo.badgeText}  
**Calculated Risk Level:** ${insight.riskLevel.value} (Confidence: ${insight.riskLevel.confidence}%)  
**Extraction Engine:** ${analysis.providerUsed} (${analysis.modelName || "Insight Analysis Engine v1.2"})  

---

## 📋 ${periodInfo.summaryLabel}
${insight.weeklySummary.value}

---

## 🎯 Primary Coach Recommendation
${insight.coachAction.value}

---

## 📊 Extracted Health & Lifestyle Metrics

### 🛌 Sleep & Circadian
- **Finding:** ${insight.sleep.value}
- **Category:** ${insight.sleep.category} (Confidence: ${insight.sleep.confidence}%)
${insight.sleep.recommendation ? `- **Recommendation:** ${insight.sleep.recommendation}` : ""}

### 🥗 Nutrition & Diet
- **Finding:** ${insight.nutritionAdherence.value}
- **Category:** ${insight.nutritionAdherence.category} (Confidence: ${insight.nutritionAdherence.confidence}%)
${insight.nutritionAdherence.recommendation ? `- **Recommendation:** ${insight.nutritionAdherence.recommendation}` : ""}

### 🏃 Physical Exercise
- **Finding:** ${insight.exercise.value}
- **Category:** ${insight.exercise.category} (Confidence: ${insight.exercise.confidence}%)
${insight.exercise.recommendation ? `- **Recommendation:** ${insight.exercise.recommendation}` : ""}

### 🚶 Steps & Mobility
- **Finding:** ${insight.steps.value}
- **Category:** ${insight.steps.category} (Confidence: ${insight.steps.confidence}%)

### 💧 Water & Hydration
- **Finding:** ${insight.waterIntake.value}
- **Category:** ${insight.waterIntake.category} (Confidence: ${insight.waterIntake.confidence}%)
${insight.waterIntake.recommendation ? `- **Recommendation:** ${insight.waterIntake.recommendation}` : ""}

### 🤒 Physical Symptoms
- **Finding:** ${insight.symptoms.value}
- **Category:** ${insight.symptoms.category} (Confidence: ${insight.symptoms.confidence}%)
${insight.symptoms.recommendation ? `- **Recommendation:** ${insight.symptoms.recommendation}` : ""}

### 😰 Stress & Workload
- **Finding:** ${insight.stress.value}
- **Category:** ${insight.stress.category} (Confidence: ${insight.stress.confidence}%)
${insight.stress.recommendation ? `- **Recommendation:** ${insight.stress.recommendation}` : ""}

---

## ⚠️ Risk Flags & Action Commitments

### Overall Risk Assessment
- **Level:** ${insight.riskLevel.value}
- **Rationale:** ${insight.riskLevel.rationale}

### Risk Flags (${insight.riskFlags.length})
${
  insight.riskFlags.length === 0
    ? "- No elevated physical or emotional risks detected."
    : insight.riskFlags
        .map((f) => `- **[${f.level} Risk] ${f.label}:** ${f.rationale}`)
        .join("\n")
}

### Pending Actions (${insight.pendingActions.length})
${
  insight.pendingActions.length === 0
    ? "- No pending client actions."
    : insight.pendingActions
        .map((a) => `- **[${a.status.toUpperCase()}]** ${a.description}`)
        .join("\n")
}

---
*Generated by Nexiora AI — Evidence-Grounded Client Intelligence Platform*
`;

  downloadFile(
    mdContent,
    `${clientName.replace(/[^a-z0-9]/gi, "_").toLowerCase()}_report.md`,
    "text/markdown;charset=utf-8;"
  );
}

export function exportReportAsJSON(analysis: AnalysisResponse): void {
  const clientName = analysis.insight.meta?.sourceLabel || "Client Consultation";
  const jsonString = JSON.stringify(analysis, null, 2);

  downloadFile(
    jsonString,
    `${clientName.replace(/[^a-z0-9]/gi, "_").toLowerCase()}_report.json`,
    "application/json;charset=utf-8;"
  );
}

export function exportReportAsPDF(analysis: AnalysisResponse): void {
  const windowRef = window.open("", "_blank");
  if (!windowRef) {
    alert("Please allow popups to generate the printable PDF report.");
    return;
  }

  const insight = analysis.insight;
  const daysCount = analysis.daysCovered.length || 1;
  const periodInfo = calculateReportingPeriod(daysCount);
  const clientName = insight.meta?.sourceLabel || "Client Consultation";

  windowRef.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>${periodInfo.title} - ${clientName}</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 40px; color: #1e293b; line-height: 1.6; }
          h1 { color: #0f172a; border-bottom: 2px solid #0284c7; padding-bottom: 8px; margin-bottom: 4px; }
          .meta { font-size: 13px; color: #64748b; margin-bottom: 24px; }
          .badge { display: inline-block; background: #e0f2fe; color: #0369a1; font-weight: bold; padding: 2px 8px; border-radius: 4px; font-size: 12px; }
          .card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; margin-bottom: 16px; }
          .card-title { font-size: 14px; font-weight: bold; color: #0284c7; margin-bottom: 6px; }
          .metric-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 24px; }
          .risk-high { background: #fef2f2; color: #991b1b; border: 1px solid #fecaca; }
          .risk-medium { background: #fffbeb; color: #92400e; border: 1px solid #fef3c7; }
          .risk-low { background: #f0fdf4; color: #166534; border: 1px solid #bbf7d0; }
          footer { margin-top: 40px; border-top: 1px solid #e2e8f0; pt: 12px; font-size: 11px; color: #94a3b8; text-align: center; }
        </style>
      </head>
      <body>
        <h1>${periodInfo.title}</h1>
        <div class="meta">
          <strong>Client / Session:</strong> ${clientName} | 
          <strong>Analyzed Period:</strong> <span class="badge">${periodInfo.badgeText}</span> | 
          <strong>Date:</strong> ${new Date().toLocaleDateString()}
        </div>

        <div class="card">
          <div class="card-title">📋 ${periodInfo.summaryLabel}</div>
          <div>${insight.weeklySummary.value}</div>
        </div>

        <div class="card">
          <div class="card-title">🎯 Primary Coach Recommendation</div>
          <div>${insight.coachAction.value}</div>
        </div>

        <h2>Extracted Health Metrics</h2>
        <div class="metric-grid">
          <div class="card"><strong>🛌 Sleep & Circadian:</strong> ${insight.sleep.value}</div>
          <div class="card"><strong>🥗 Nutrition & Diet:</strong> ${insight.nutritionAdherence.value}</div>
          <div class="card"><strong>🏃 Physical Exercise:</strong> ${insight.exercise.value}</div>
          <div class="card"><strong>🚶 Steps & Mobility:</strong> ${insight.steps.value}</div>
          <div class="card"><strong>💧 Water & Hydration:</strong> ${insight.waterIntake.value}</div>
          <div class="card"><strong>🤒 Physical Symptoms:</strong> ${insight.symptoms.value}</div>
          <div class="card"><strong>😰 Stress & Workload:</strong> ${insight.stress.value}</div>
          <div class="card"><strong>⚡ Engagement Level:</strong> ${insight.engagementLevel.value}</div>
        </div>

        <h2>Risk Assessment</h2>
        <div class="card ${insight.riskLevel.value === "High" ? "risk-high" : insight.riskLevel.value === "Medium" ? "risk-medium" : "risk-low"}">
          <strong>Overall Risk Level: ${insight.riskLevel.value}</strong><br/>
          ${insight.riskLevel.rationale}
        </div>

        <footer>
          Generated by Nexiora AI — Evidence-Grounded Client Intelligence Platform
        </footer>

        <script>
          window.onload = function() { window.print(); }
        </script>
      </body>
    </html>
  `);
  windowRef.document.close();
}

function downloadFile(content: string, fileName: string, contentType: string) {
  const a = document.createElement("a");
  const file = new Blob([content], { type: contentType });
  a.href = URL.createObjectURL(file);
  a.download = fileName;
  a.click();
  URL.revokeObjectURL(a.href);
}
